// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearTempImages():Promise<void>;

export function DeleteSingleImage(arg1:string):Promise<void>;

export function ExportQuestionBank(arg1:string):Promise<string>;

export function GetImageList():Promise<Array<main.ImageInfo>>;

export function ImportQuestionBank():Promise<string>;

export function PreviewQuestionBank(arg1:string):Promise<string>;

export function ProcessPendingDeleteImages(arg1:string):Promise<void>;

export function SaveImage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function SelectSaveFolder():Promise<string>;

export function ValidateQuestionBank(arg1:string):Promise<Array<string>>;
