// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTempImages() {
  return window['go']['main']['App']['ClearTempImages']();
}

export function DeleteSingleImage(arg1) {
  return window['go']['main']['App']['DeleteSingleImage'](arg1);
}

export function ExportQuestionBank(arg1) {
  return window['go']['main']['App']['ExportQuestionBank'](arg1);
}

export function GetImageList() {
  return window['go']['main']['App']['GetImageList']();
}

export function ImportQuestionBank() {
  return window['go']['main']['App']['ImportQuestionBank']();
}

export function PreviewQuestionBank(arg1) {
  return window['go']['main']['App']['PreviewQuestionBank'](arg1);
}

export function ProcessPendingDeleteImages(arg1) {
  return window['go']['main']['App']['ProcessPendingDeleteImages'](arg1);
}

export function SaveImage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectSaveFolder() {
  return window['go']['main']['App']['SelectSaveFolder']();
}

export function ValidateQuestionBank(arg1) {
  return window['go']['main']['App']['ValidateQuestionBank'](arg1);
}
